version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for php
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
